# Generated by Django 5.2.11 on 2026-02-25 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('panel_type', models.CharField(choices=[('AUTOMATION', 'Automation'), ('DISTRIBUTION', 'Distribution')], max_length=16)),
                ('wizard_step', models.CharField(choices=[('STEP1', 'Step 1'), ('STEP2', 'Step 2'), ('STEP3', 'Step 3'), ('DONE', 'Done')], default='STEP1', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
