# Generated by Django 5.2.11 on 2026-02-25 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalParams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voltage_v', models.PositiveIntegerField()),
                ('frequency_hz', models.PositiveIntegerField(default=60)),
                ('phase_system', models.CharField(choices=[('1P', '1~'), ('3P', '3~')], max_length=2)),
                ('has_neutral', models.BooleanField(default=False)),
                ('icc_value_ka', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('icc_range_ka', models.CharField(blank=True, choices=[('6', '6kA'), ('10', '10kA'), ('15', '15kA'), ('25', '25kA')], max_length=2, null=True)),
                ('control_voltage', models.CharField(default='24VDC', max_length=16)),
                ('ambient_temp_c', models.PositiveIntegerField(default=35)),
                ('ip_rating', models.CharField(default='IP54', max_length=10)),
                ('standard', models.CharField(default='IEC_60204_1', max_length=32)),
                ('has_drives_emc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_params', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('MOTOR', 'Motor'), ('RESISTIVE', 'Resistive'), ('AUX', 'Aux'), ('DC24', '24Vdc')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Dc24Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('PLC', 'PLC'), ('IHM', 'IHM'), ('SENSORS', 'Sensors'), ('VALVES', 'Valves'), ('RELAYS', 'Relays'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=16)),
                ('current_a', models.DecimalField(decimal_places=3, default=0.1, max_digits=8)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc24', to='specs.load')),
            ],
        ),
        migrations.CreateModel(
            name='AuxLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_current_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aux', to='specs.load')),
            ],
        ),
        migrations.CreateModel(
            name='MotorLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('power_kw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('voltage_v', models.PositiveIntegerField()),
                ('drive_type', models.CharField(choices=[('DOL', 'DOL'), ('SOFTSTARTER', 'Softstarter'), ('VFD', 'VFD'), ('SERVO', 'Servo')], max_length=16)),
                ('cosphi', models.DecimalField(decimal_places=2, default=0.85, max_digits=4)),
                ('efficiency', models.DecimalField(decimal_places=2, default=0.9, max_digits=4)),
                ('duty', models.CharField(default='S1', max_length=10)),
                ('motor_cable_length_m', models.PositiveIntegerField(blank=True, null=True)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='specs.load')),
            ],
        ),
        migrations.CreateModel(
            name='ResistiveLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('power_kw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('voltage_v', models.PositiveIntegerField()),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resistive', to='specs.load')),
            ],
        ),
    ]
