# Generated by Django 5.2.11 on 2026-02-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalparams',
            name='has_main_isolation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electricalparams',
            name='main_isolation_type',
            field=models.CharField(blank=True, choices=[('DISCONNECTOR', 'Seccionadora'), ('MCCB', 'Disjuntor Caixa Moldada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electricalparams',
            name='mccb_external_handle_model',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='electricalparams',
            name='mccb_has_external_handle',
            field=models.BooleanField(default=False),
        ),
    ]
