# Generated by Django 5.2.11 on 2026-02-25 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=40)),
                ('manufacturer', models.CharField(default='SIEMENS', max_length=40)),
                ('part_number', models.CharField(default='TBD', max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bomsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('ERROR', 'Error'), ('WARN', 'Warn'), ('INFO', 'Info')], max_length=10)),
                ('code', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='projects.project')),
            ],
        ),
    ]
